apiVersion: apps/v1
kind: Deployment
metadata:
  name: promptguard
  labels:
    app: promptguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promptguard
  template:
    metadata:
      labels:
        app: promptguard
    spec:
      containers:
        - name: promptguard
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8000
          env:
            - name: GEMINI_API_KEY
              value: "dummy"
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
